import {
  SiReact,
  SiTypescript,
  SiNextdotjs,
  SiTailwindcss,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiRedux,
  SiNodedotjs,
  SiExpress,
  SiPython,
  SiPostgresql,
  SiMongodb,
  SiPostman,
  SiGit,
  SiDocker,
  SiGithubactions,
  SiVscodium,
  SiFigma,
  SiSpringboot,
  SiFlask,
  SiDjango,
  SiApachemaven,
  SiJenkins,
  SiIntellijidea,
  SiJupyter,
  SiJest,
  SiPytest,
  SiKubernetes,
  SiDatadog,
  SiMysql,
  SiRedis,
  SiScikitlearn,
  SiTensorflow,
  SiPytorch,
  SiPandas,
  SiNumpy,
} from "react-icons/si";
import { FaAws, FaJava, FaMicrosoft } from "react-icons/fa";
import { BsArrowRepeat } from "react-icons/bs";
import type { IconType } from "react-icons";

const iconMap: Record<string, IconType> = {
  SiReact,
  SiTypescript,
  SiNextdotjs,
  SiTailwindcss,
  SiJavascript,
  SiHtml5,
  SiCss,
  SiRedux,
  SiNodedotjs,
  SiExpress,
  SiPython,
  SiPostgresql,
  SiMongodb,
  SiPostman,
  SiGit,
  SiDocker,
  FaAws,
  SiGithubactions,
  SiVscodium,
  SiFigma,
  SiSpringboot,
  SiFlask,
  SiDjango,
  SiApachemaven,
  SiJenkins,
  SiIntellijidea,
  SiJupyter,
  SiJest,
  SiPytest,
  SiKubernetes,
  SiDatadog,
  SiMysql,
  SiRedis,
  SiScikitlearn,
  SiTensorflow,
  SiPytorch,
  SiPandas,
  SiNumpy,
  java: FaJava,
  springboot: SiSpringboot,
  flask: SiFlask,
  django: SiDjango,
  restapi: BsArrowRepeat,
  maven: SiApachemaven,
  jenkins: SiJenkins,
  intellij: SiIntellijidea,
  jupyter: SiJupyter,
  jest: SiJest,
  pytest: SiPytest,
  kubernetes: SiKubernetes,
  datadog: SiDatadog,
  mysql: SiMysql,
  redis: SiRedis,
  scikitlearn: SiScikitlearn,
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  pandas: SiPandas,
  numpy: SiNumpy,
  azure: FaMicrosoft,
};

interface Props {
  name: string;
  className?: string;
}

export default function SkillIcon({ name, className = "text-2xl" }: Props) {
  const Icon = iconMap[name];
  if (!Icon) return null;
  return <Icon className={className} />;
}
